name: CI/CD - Docker Push

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/docker-flask-ci . --load

    - name: Push to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-flask-ci

